baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Bitácora'
theme: 'dina'
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: base16-snazzy
    tabWidth: 4


params:
  brandname: 'tdinapoli@bitacora'
  mainsections:
  - posts
  bootstrap: 'legacy'

menu:
  main:
  - name: sobre-mi
    url: /about/
    weight: 90
  - name: posts
    url: /posts/
    weight: 100

